services:
  app:
    build: .
    container_name: notes_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_NAME: notes
      DB_USER: notes_server
      DB_PASSWORD: password
      DB_HOST: "db"
      DB_PORT: "5432"

  db:
    image: registry.docker.ir/postgres:16.3-alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notes_server
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
